# Generated by Django 5.1.5 on 2025-01-29 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0006_rename_trainingsession_training_session'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Training_session',
            new_name='Session',
        ),
    ]
