# Generated by Django 5.1.5 on 2025-01-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0008_team_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(default='/img/team_badge.png', upload_to=''),
        ),
    ]
