# Generated by Django 5.1.5 on 2025-01-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0011_alter_team_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, default='/team_badge.png', null=True, upload_to=''),
        ),
    ]
