# Generated by Django 5.1.5 on 2025-01-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0012_alter_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='hash',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
