# Generated by Django 5.1.5 on 2025-01-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Coach', 'Coach'), ('Parent', 'Parent'), ('Player', 'Player')], default='Player', max_length=20, null=True),
        ),
    ]
