# Generated by Django 5.1.5 on 2025-01-26 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_player_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
