# Generated by Django 5.1.5 on 2025-01-29 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0003_team_coach'),
        ('user', '0002_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coach.team'),
        ),
    ]
